apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  namespace: jenkins-app
  labels:
    app: jenkins-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
        - name: jenkins-app
          image: ahmedsabeh/jenkins-app:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  namespace: jenkins-app
spec:
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

