name: CI/CD Pipeline to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build the Maven project
      - name: Build with Maven
        run: mvn -B clean package --file App/pom.xml

      # 4️⃣ Upload the JAR as artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: App/target/*.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6️⃣ Log in to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 7️⃣ Build and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY }}
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_URI:$TAG App
          docker push $IMAGE_URI:$TAG
          echo "IMAGE=$IMAGE_URI:$TAG" >> $GITHUB_ENV

